name: Build GDExtension
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        target: [
            { platform: macos, arch: universal, os: macos-latest },
            { platform: linux, arch: x86_64, os: ubuntu-22.04 },
            # { platform: ios, arch: arm64, os: macos-latest },
            # { platform: windows, arch: x86_64, os: windows-latest },
            # { platform: android, arch: arm64, os: ubuntu-22.04 },
          ]
        target-type: [template_debug, template_release]
        float-precision: [single]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      # Build GDExtension (with caches)

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension Debug Build
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }}

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-imgui-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/bin/**

  # Merges all the build artifacts together into a single godot-imgui artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: godot-imgui-*
          path: artifacts

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: godot-imgui-*

      - name: Create addons folder structure
        shell: sh
        run: |
          mkdir -p upload/addons/godot-imgui
          cp -r artifacts/*/* upload/addons/godot-imgui
          cp demo/bin/godot-imgui.gdextension upload/addons/godot-imgui/

      - name: Upload addons artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-imgui-addon
          path: upload/
